name: Build jars

on:
  workflow_dispatch:

jobs:
  buildJar:
    strategy:
      fail-fast: false
      matrix:
        versions_branch: ["master", "1.16.5", "1.20.1"]
    name: Build jar (${{ matrix.versions_branch }})
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: "${{ matrix.versions_branch }}"
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "oracle"
          cache: "gradle"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Gradle build
        run: ./gradlew build
      - name: Upload jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: buildJar-${{ matrix.versions_branch }}-${{ github.run_id }}-java17
          path: './build/libs/*.jar'
          retention-days: 30
          overwrite: "true"
