name: Build jars

on:
  push:
    branches:
      - "1.20.4"
    paths:
      - src/**/*.java
      - src/resources/
      - "build.gradle"
      - "gradle.properties"
      - "settings.gradle"
      - "!README.md"
      - "!LICENSE"
      - "!CHANGELOG.md"
  workflow_dispatch:

jobs:
  buildJar:
    name: Build jar 1.20.4
    uses: CrimsonEdgeHope/SocksProxyClientOfMinecraft/.github/workflows/jar.yml@master
    with:
      build-ref: "1.20.4"
      java-version: "17"
      java-distribution: "oracle"
