name: Build jars

on:
  push:
    branches:
      - "1.21.4"
    paths:
      - src/**/*.java
      - src/resources/
      - "build.gradle"
      - "gradle.properties"
      - "settings.gradle"
      - "!README.md"
      - "!LICENSE"
      - "!CHANGELOG.md"
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  buildJar:
    name: Build jar 1.21.4
    uses: NorthRealm/SocksProxyClientOfMinecraft/.github/workflows/jar.yml@master
    with:
      build-ref: "1.21.4"
      java-version: "21"
      java-distribution: "oracle"
