name: Build jars

on:
  workflow_call:
    inputs:
      build-ref:
        type: string
        required: true
      java-version:
        type: string
        required: true
      java-distribution:
        type: string
        required: false
        default: "oracle"

jobs:
  buildJar:
    name: Build jar (${{ inputs.build-ref }})
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: "${{ inputs.build-ref }}"
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "${{ inputs.java-version }}"
          distribution: "${{ inputs.java-distribution }}"
          cache: "gradle"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Gradle build
        run: ./gradlew build
      - name: Upload jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: buildJar-${{ inputs.build-ref }}-${{ github.run_id }}
          path: './build/libs/*.jar'
          retention-days: 30
          overwrite: "true"
