name: Build jar 1.16.5

on:
  push:
    branches:
      - "1.16.5"
    paths:
      - src/**/*.java
      - src/resources/
      - "build.gradle"
      - "gradle.properties"
      - "settings.gradle"
      - "!README.md"
      - "!LICENSE"
      - "!CHANGELOG.md"
  workflow_dispatch:

jobs:
  buildJar:
    name: Build jar 1.16.5
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: "${{ github.sha }}"
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "oracle"
          cache: "gradle"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Gradle build
        run: ./gradlew build
      - name: Upload jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: buildJar-${{ github.sha }}-${{ github.run_id }}-java17
          path: './build/libs/*.jar'
          retention-days: 30
          overwrite: "true"
