name: Publish release

on:
  workflow_call:
    inputs:
      tag-ref:
        type: string
        required: true
      java-version:
        type: string
        required: true
      java-distribution:
        type: string
        required: false
        default: "oracle"
    secrets:
      MODRINTH_TOKEN:
        required: true

permissions:
  contents: write

jobs:
  publish-release:
    name: Publish release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag-ref }}
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "${{ inputs.java-version }}"
          distribution: "${{ inputs.java-distribution }}"
          cache: "gradle"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Gradle build
        run: ./gradlew build
      - name: Changelog body
        id: get_changelog_body
        run: |
          touch tmp_changelog_body.txt
          echo "$(./gradlew getChangelog --console=plain --quiet --no-links --no-empty-sections --no-summary)" > tmp_changelog_body.txt
        shell: bash
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          body_path: tmp_changelog_body.txt
          prerelease: ${{ contains(github.event.head_commit.message, '[prerelease]') }}
          files: |
            build/libs/*-SNAPSHOT.jar
      - name: Publish to Modrinth
        run: ./gradlew modrinth -Pverbose=true
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
