name: Publish release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  publish-release:
    name: Publish release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "oracle"
          cache: "gradle"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Gradle build
        run: ./gradlew build
      - name: Changelog body
        id: get_changelog_body
        run: |
          CHANGELOG_BODY=$(./gradlew getChangelog --console=plain --quiet --no-links --no-empty-sections --no-summary)
          echo "$CHANGELOG_BODY" >> $GITHUB_OUTPUT
        shell: bash
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          body: ${{ steps.get_changelog_body.outputs.CHANGELOG_BODY }}
          prerelease: ${{ contains(github.event.head_commit.message, '[prerelease]') }}
          files: |
            build/libs/*-SNAPSHOT.jar
