name: Publish release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  publish-release:
    name: Publish release
    uses: CrimsonEdgeHope/SocksProxyClientOfMinecraft/.github/workflows/release.yml@master
    with:
      tag-ref: ${{ github.ref }}
      java-version: "17"
      java-distribution: "oracle"
    secrets:
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
